name: Delete old workflow runs
on:
# Run weekly, at 00:00 on sunday.
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs for remote repo
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: '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'
          repository: 'alalbb313/rustdesk'
          retain_days: 0
          keep_minimum_runs: 1
